spring:
  application:
    name: nerya-all-naturals
  datasource:
    url: jdbc:mysql://mysql:3306/nerya?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: nerya
    password: change-me
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

server:
  port: 8080
  servlet:
    context-path: /

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui

logging:
  level:
    com.nerya.neryaallnaturals: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
